### ISSUE TITLE
About X and Y naming in easyzoom.js

### ISSUE THREAD

**Issue by mythnc** [i-like-robots/EasyZoom#131]
First, thanks for open source your source code, and I learn a lot from it.

I have a small question about the naming `relativePositionX` and `relativePositionY` in 
https://github.com/i-like-robots/EasyZoom/blob/master/src/easyzoom.js#L247

Is there any reason to treat Y as X and X as Y...?

I just kind of confused. Thanks.

**Comment by i-like-robots** [comment]
It's a mistake, also the `moveX` and `moveY` variables below seem to be the wrong way round too 🤦 

When I inititally wrote the component I used very short variable names which I had to expand a few years ago in order to fix a bug (https://github.com/i-like-robots/EasyZoom/commit/44acacc0c0b45f8be4107881223b67a66aabbb2f#diff-d22e25e9aee22ceaa10af787bd6c347a) - during this process I must have gotten mixed up.
