### ISSUE TITLE
Zoom does not work from the right side

### ISSUE THREAD

**Issue by arsistyle** [i-like-robots/EasyZoom#82]
the container zoom does not appear when the mouse enters the right side, only works from the top, bottom and left.

[link to demo of the problem](http://locasdeatar.feline.cl/catalogo/sandalias/zapatillas-4)

thnks for the help :)

**Comment by i-like-robots** [comment]
Place the `.easyzoom` element inside of your column element. The column element has padding which means the image is not being shrink wrapped as explained [in the setup docs](http://i-like-robots.github.io/EasyZoom/#setup).

Currently the mouse enters the easyzoom element and the flyout is displayed, but, it's being immediately removed because the cursor is not over the image.

**Comment by nicodezu** [comment]
I have `.easyzoom` on my column but it don' work too.
My css is that:
`.easyzoom {
    position: relative;

    /* 'Shrink-wrap' the element */
    display: inline-block;
    *display: inline;
    *zoom: 1;
}

.easyzoom img {
    vertical-align: bottom;
}`

**Comment by nicodezu** [comment]
> I have .easyzoom on my column but it don' work too.
My css is that:
.easyzoom { position: relative; /* 'Shrink-wrap' the element */ display: inline-block; *display: inline; *zoom: 1; }
.easyzoom img { vertical-align: bottom; }
I look inside code of easyzoom.js and when i go from right to image code enter on this control
if (xl < 0 || xt < 0 || xl > dw || xt > dh) {
// enter
this.hide();
}
meanwhile if I enter on other side code not enter on if. Maybe there is there the problem

Someone found solution?

**Comment by nicodezu** [comment]
up

**Comment by nicodezu** [comment]
I trough solution about problem of enter on image from right to left.
I have a padding of 15px on left and on right but only on enter from right I have error that image not zoom.
I insert `style="padding:0px !important"` on div of `easyzoom` class and I resolve problem

**Comment by bobypenev** [comment]
I had this issue happen on random images (immediately hiding) when accessed from right or bottom, without any padding on the elements.

This line hides it improperly: `if (moveY < 0 || moveX < 0 || moveY > zoomImgOverlapX || moveX > zoomImgOverlapY)`. 

Logging `moveX` and `zoomImgOverlapY`, turned out they are `26` and `25.90599999999995`. :) Same issue with the other `>` comparison. So that's why it happens randomly, depending on image dimensions.

So the solution was to ceil `zoomImgOverlapX` and `zoomImgOverlapY` inside the `show` method:

```
zoomImgOverlapX = Math.ceil(zoomImgWidth - flyoutInnerWidth);
zoomImgOverlapY = Math.ceil(zoomImgHeight - flyoutInnerHeight);
```

**Comment by i-like-robots** [comment]
Rounding up the figures seems like a sensible thing to do, if you fancy submitting a pull request for this change @bobypenev I'd be happy to accept it 😄
