### ISSUE TITLE
Adjacent image doesn't display when viewport zoomed

### ISSUE THREAD

**Issue by aletaschner** [i-like-robots/EasyZoom#98]
Hello. I don't exactly know if this is a bug, a bad configuration by me or actually expected behaviour. When on mobile, if I zoom in next to the images and then touch for them to show, nothing happens at all, but if I leave the zoom they work as expected.

I have a production example, the zoom I'm referring to is inside the "FIBRA" select box.
Link: [http://bit.ly/2d6ZN8Q](http://bit.ly/2d6ZN8Q)

Thanks for your time! :+1:

**Comment by aletaschner** [comment]
Nothing? :/

**Comment by i-like-robots** [comment]
At first i thought this issue was related to #82 and #94 but upon investigation I can see that the `mouseenter` event is triggered as expected and the internal `show` method called, however `hide` is immediately called after that due to the third constraint in this condition:

https://github.com/i-like-robots/EasyZoom/blob/master/src/easyzoom.js#L236

Now [the maths behind this](https://github.com/i-like-robots/EasyZoom/commit/0223b719243c2d2dcf267476ea1db29fdc55e309) are long forgotten and the my variable naming choices in 2011 were not so great.
